### ISSUE TITLE
TODO #1

### ISSUE THREAD

**Issue by falseresync** [falseresync/wizcraft#1]
- [ ] Make Lensed worktable play "crafting" music
- [ ] Add custom sounds to much of everything
- [ ] Improve Worktable textures and model
- [x] Make Lensed worktable drop items when broken
- [ ] Add Charging mode to the Worktable
- [ ] Add a visual Comet Warp beacon
- [x] Animate Lensed worktable crafting
- [ ] Animate Worktable wand charging
- [ ] Animate Wand charging in hand
- [x] Make all focuses use Report system
- [x] Make Comet Warp focus cost differ for interdimensional travel
- [x] Make Starshooter focus area-of-effect

**Comment by falseresync** [comment]
Superceded by Trello
